- make decoder_input by slice target
- get next_token by slice output

In [19]:
import tensorflow as tf

batch_size = 4
max_seq_len = 10
decoder_index = 5

sess = tf.InteractiveSession()
decoder_inputs = tf.reshape(tf.range(0, batch_size*max_seq_len), [batch_size, max_seq_len])

print("decoder_inputs or output")
print(decoder_inputs.eval())
print()

next_token = tf.slice(decoder_inputs, [0, decoder_index], [batch_size, 1])

print("slice decoder_index")
print(next_token.eval())
print()

target_slice_last_1 = tf.slice(decoder_inputs, [0, 0], [batch_size, max_seq_len-1])

print("slice for target")
print(target_slice_last_1.eval())
print()

sess.close()

decoder_inputs or output
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]

slice decoder_index
[[ 5]
 [15]
 [25]
 [35]]

slice for target
[[ 0  1  2  3  4  5  6  7  8]
 [10 11 12 13 14 15 16 17 18]
 [20 21 22 23 24 25 26 27 28]
 [30 31 32 33 34 35 36 37 38]]



- mode : Evaluattion or Predict
- predict output with loop. [encoder_outputs, decoder_inputs (filled next token)]

In [19]:
import tensorflow as tf

batch_size = 4
max_seq_len = 10
decoder_index = 5

sess = tf.InteractiveSession()
decoder_inputs = tf.reshape(tf.range(0, 20), [batch_size, 5])
zero_pads = tf.zeros([batch_size, 5], dtype=tf.int32)
decoder_inputs = tf.concat((decoder_inputs, zero_pads), axis=1)

print("decoder_inputs.")
print(decoder_inputs.eval())
print()

# next_token [21, 22, 23, 24] 
# -> make tensor shape [batch_size, max_seq_len], have value decoder_index
next_token = tf.reshape(tf.constant([21, 22, 23, 24]), [batch_size, 1])
left_zero_pads = tf.zeros([batch_size, decoder_index], dtype=tf.int32)
right_zero_pads = tf.zeros([batch_size, (max_seq_len-decoder_index-1)], dtype=tf.int32)

next_token = tf.concat((left_zero_pads, next_token, right_zero_pads), axis=1)

print("next_token")
print(next_token.eval())
print()

decoder_inputs = decoder_inputs + next_token
# We can just use 'c.eval()' without passing 'sess'

print("next decoder_inputs.")
print(decoder_inputs.eval())
print()

sess.close()

decoder_inputs.
[[ 0  1  2  3  4  0  0  0  0  0]
 [ 5  6  7  8  9  0  0  0  0  0]
 [10 11 12 13 14  0  0  0  0  0]
 [15 16 17 18 19  0  0  0  0  0]]

next_token
[[ 0  0  0  0  0 21  0  0  0  0]
 [ 0  0  0  0  0 22  0  0  0  0]
 [ 0  0  0  0  0 23  0  0  0  0]
 [ 0  0  0  0  0 24  0  0  0  0]]

next decoder_inputs.
[[ 0  1  2  3  4 21  0  0  0  0]
 [ 5  6  7  8  9 22  0  0  0  0]
 [10 11 12 13 14 23  0  0  0  0]
 [15 16 17 18 19 24  0  0  0  0]]



In [20]:
import tensorflow as tf

batch_size = 4
max_seq_len = 10
decoder_index = 9

sess = tf.InteractiveSession()
decoder_inputs = tf.reshape(tf.range(0, 20), [batch_size, 5])
zero_pads = tf.zeros([batch_size, 5], dtype=tf.int32)
decoder_inputs = tf.concat((decoder_inputs, zero_pads), axis=1)

print("decoder_inputs.")
print(decoder_inputs.eval())
print()

# next_token [21, 22, 23, 24] 
# -> make tensor shape [batch_size, max_seq_len], have value decoder_index
next_token = tf.reshape(tf.constant([21, 22, 23, 24]), [batch_size, 1])
left_zero_pads = tf.zeros([batch_size, decoder_index], dtype=tf.int32)
right_zero_pads = tf.zeros([batch_size, (max_seq_len-decoder_index-1)], dtype=tf.int32)

next_token = tf.concat((left_zero_pads, next_token, right_zero_pads), axis=1)

print("next_token")
print(next_token.eval())
print()

decoder_inputs = decoder_inputs + next_token
# We can just use 'c.eval()' without passing 'sess'

print("next decoder_inputs.")
print(decoder_inputs.eval())
print()

sess.close()

decoder_inputs.
[[ 0  1  2  3  4  0  0  0  0  0]
 [ 5  6  7  8  9  0  0  0  0  0]
 [10 11 12 13 14  0  0  0  0  0]
 [15 16 17 18 19  0  0  0  0  0]]

next_token
[[ 0  0  0  0  0  0  0  0  0 21]
 [ 0  0  0  0  0  0  0  0  0 22]
 [ 0  0  0  0  0  0  0  0  0 23]
 [ 0  0  0  0  0  0  0  0  0 24]]

next decoder_inputs.
[[ 0  1  2  3  4  0  0  0  0 21]
 [ 5  6  7  8  9  0  0  0  0 22]
 [10 11 12 13 14  0  0  0  0 23]
 [15 16 17 18 19  0  0  0  0 24]]

